Criar versão inicial do gerador de ficha para 3DeT/ Front-End
tbitencourt/fichaonline-web pull request #2
Opened 2023-09-11 20:08 UTC by tbitencourt

Link: https://trello.com/c/TXcQC7xe/11-criar-vers%C3%A3o-inicial-do-gerador-de-ficha-para-3det-front-end

2023-09-11 21:06 UTC, the-one-who-knoccks requested changes

2023-09-19 13:42 UTC, the-one-who-knoccks commented on src/pages/CharacterSheetCreation/components/Attribute/index.tsx
> +          <label htmlFor="power">P: </label>
Seria interessate colocar um tooltip para cada atributo.

2023-09-19 20:47 UTC, betobala commented on src/pages/CharacterSheetCreation/components/Attribute/index.tsx
> +          <label htmlFor="power">P: </label>
Tooltip adicionado.

2023-09-20 00:54 UTC, the-one-who-knoccks approved these changes

2023-09-22 19:36 UTC, merged